# Generated by Django 3.2.20 on 2023-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islandersdogdaycare', '0002_comment_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='bring_own_food',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='up_to_date_vaccinations',
        ),
        migrations.AddField(
            model_name='dog',
            name='food_provided',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccinations_up_to_date',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
    ]
