# Generated by Django 3.2.20 on 2023-08-27 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('islandersdogdaycare', '0004_auto_20230827_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
