# Generated by Django 3.2.20 on 2023-08-28 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('islandersdogdaycare', '0005_auto_20230827_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='owner',
        ),
        migrations.AddField(
            model_name='owner',
            name='email_address',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islandersdogdaycare.dog'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Testimonials', to='auth.user'),
        ),
    ]
