# Generated by Django 3.2.20 on 2023-08-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('islandersdogdaycare', '0006_auto_20230828_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='islandersdogdaycare.owner'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, related_name='Testimonials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExtraInfo',
        ),
    ]
