# Generated by Django 3.2.20 on 2023-08-30 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islandersdogdaycare', '0007_auto_20230828_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dog',
            name='food_provided',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='vaccinations_up_to_date',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email_address',
            field=models.EmailField(default='Enter your email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(default='Please enter your name', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_daycare',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
