# Generated by Django 3.2.20 on 2023-08-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islandersdogdaycare', '0008_auto_20230830_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(default='Enter your name', max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='tel_no',
            field=models.CharField(default='Enter your phone number', max_length=15),
        ),
    ]
