# Generated by Django 3.2.20 on 2023-09-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('islandersdogdaycare', '0010_auto_20230913_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='excerpt',
        ),
    ]
